const GENRE_TRANSLATIONS: Record<string, string> = {
  // General
  Fiction: "Ficción",
  "Nonfiction": "No ficción",
  "Non-fiction": "No ficción",
  Fantasy: "Fantasía",
  "Science Fiction": "Ciencia ficción",
  Mystery: "Misterio",
  Thriller: "Thriller",
  Horror: "Terror",
  Romance: "Romance",
  Drama: "Drama",
  Comedy: "Comedia",
  Adventure: "Aventura",
  Action: "Acción",
  Poetry: "Poesía",
  "Short Stories": "Cuentos",
  "Graphic Novel": "Novela gráfica",
  "Children's Fiction": "Ficción infantil",
  "Young Adult": "Juvenil",
  "Young Adult Fiction": "Ficción juvenil",
  "Classic Literature": "Literatura clásica",
  "Historical Fiction": "Ficción histórica",
  "Literary Fiction": "Ficción literaria",
  "Romance literature": "Literatura romántica",
  "Romance Literature": "Literatura romántica",
  "Spanish Literature": "Literatura española",
  "Catalan Literature": "Literatura catalana",
  "Latin American Literature": "Literatura latinoamericana",
  "English Literature": "Literatura inglesa",
  "American Literature": "Literatura americana",
  "World Literature": "Literatura universal",
  "Detective Fiction": "Novela policiaca",
  "Crime Fiction": "Ficción criminal",
  "Science fiction": "Ciencia ficción",
  "Juvenile Fiction": "Ficción juvenil",
  "Juvenile Nonfiction": "No ficción juvenil",
  "Picture books": "Álbum ilustrado",
  "Picture Books": "Álbum ilustrado",
  Juvenile: "Juvenil",
  Folklore: "Folclore",
  Mythology: "Mitología",
  Comics: "Cómics",
  Manga: "Manga",
  "Erotic fiction": "Ficción erótica",
  Erotica: "Erótica",
  Paranormal: "Paranormal",
  "Paranormal Romance": "Romance paranormal",
  Suspense: "Suspense",
  "Western fiction": "Western",
  Western: "Western",
  "True Crime": "Crimen real",
  Journalism: "Periodismo",
  Essays: "Ensayo",
  Essay: "Ensayo",
  // Non-fiction
  History: "Historia",
  Biography: "Biografía",
  Autobiography: "Autobiografía",
  Memoir: "Memorias",
  Philosophy: "Filosofía",
  Psychology: "Psicología",
  Science: "Ciencia",
  Technology: "Tecnología",
  Politics: "Política",
  Economics: "Economía",
  Business: "Negocios",
  "Self-help": "Autoayuda",
  "Self Help": "Autoayuda",
  Health: "Salud",
  "Mental Health": "Salud mental",
  Sex: "Sexo",
  Travel: "Viajes",
  Cooking: "Cocina",
  Art: "Arte",
  Music: "Música",
  Sports: "Deportes",
  Religion: "Religión",
  Spirituality: "Espiritualidad",
  Education: "Educación",
  Language: "Lengua",
  Nature: "Naturaleza",
  Environment: "Medioambiente",
  // Themes
  Feminism: "Feminismo",
  "Social Issues": "Problemas sociales",
  "Coming of Age": "Iniciación",
  Family: "Familia",
  Love: "Amor",
  War: "Guerra",
  Genres: "Géneros",
  // Extra Google Books / Open Library genres
  Strangers: "Desconocidos",
  "Railroad travel": "Viajes en tren",
  Commuters: "Viajeros",
  "Train travel": "Viajes en tren",
  "Interpersonal relations": "Relaciones personales",
  "Missing persons": "Personas desaparecidas",
  "Murder victims": "Víctimas de asesinato",
  "Murder investigation": "Investigación criminal",
  "Female friendship": "Amistad femenina",
  "Married women": "Mujeres casadas",
  "Married people": "Matrimonio",
  "Love triangles": "Triángulos amorosos",
  "Triangles (Interpersonal relations)": "Triángulos amorosos",
  "Grief": "Duelo",
  "Loss (Psychology)": "Duelo",
  "Betrayal": "Traición",
  "Secrets": "Secretos",
  "Voyeurs": "Voyeurs",
  "Alcoholism": "Alcoholismo",
  "Memory": "Memoria",
  Contemporary: "Contemporáneo",
  "Contemporary fiction": "Ficción contemporánea",
  "Contemporary romance": "Romance contemporáneo",
  "Man-woman relationships": "Relaciones",
  "Love stories": "Historias de amor",
  "Domestic fiction": "Ficción doméstica",
  "Psychological fiction": "Ficción psicológica",
  "Psychological thriller": "Thriller psicológico",
  "Legal thriller": "Thriller legal",
  "Medical thriller": "Thriller médico",
  "Political fiction": "Ficción política",
  "Action & Adventure": "Acción y aventura",
  "Action and Adventure": "Acción y aventura",
  "Epic fantasy": "Fantasía épica",
  "Urban fantasy": "Fantasía urbana",
  "Dark fantasy": "Fantasía oscura",
  "Fantasy fiction": "Fantasía",
  "Science fiction & fantasy": "Ciencia ficción y fantasía",
  "Science fiction and fantasy": "Ciencia ficción y fantasía",
  "Horror fiction": "Terror",
  "Ghost stories": "Historias de fantasmas",
  "Detective and mystery stories": "Misterio y detectives",
  "Mystery & Detective": "Misterio y detective",
  "Murder mystery": "Misterio de asesinato",
  "Cozy mystery": "Misterio tranquilo",
  "Chick-lit": "Chick-lit",
  "Women's fiction": "Ficción femenina",
  "General fiction": "Ficción general",
  "Adult fiction": "Ficción adulta",
  "Erotic romance": "Romance erótico",
  "New Adult": "New adult",
  "Dystopian fiction": "Ficción distópica",
  Dystopia: "Distopía",
  "Post-apocalyptic fiction": "Postapocalíptico",
  "Time travel": "Viaje en el tiempo",
  "Alternate history": "Historia alternativa",
  "Steampunk fiction": "Steampunk",
  Steampunk: "Steampunk",
  "True story": "Historia real",
  "Personal development": "Desarrollo personal",
  Mindfulness: "Mindfulness",
  "Mental illness": "Enfermedad mental",
  Relationships: "Relaciones",
  Sexuality: "Sexualidad",
  "LGBTQ+": "LGBTQ+",
  LGBTQ: "LGBTQ+",
  "Gay & Lesbian": "LGBTQ+",
  Gardening: "Jardinería",
  Parenting: "Crianza",
  "Humor / Satire": "Humor y sátira",
  Humor: "Humor",
  Satire: "Sátira",
  Classics: "Clásicos",
  Epic: "Epopeya",
  Fable: "Fábula",
  Fairy: "Cuento de hadas",
  "Fairy tales": "Cuentos de hadas",
  "Short stories": "Cuentos",
  Anthology: "Antología",
  Plays: "Teatro",
  Theatre: "Teatro",
};

const LOWER_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(GENRE_TRANSLATIONS).map(([k, v]) => [k.toLowerCase(), v])
);

export function translateGenre(genre: string): string {
  return GENRE_TRANSLATIONS[genre] ?? LOWER_MAP[genre.toLowerCase()] ?? genre;
}
